### ISSUE TITLE
Fix Accessibility Issues from AChecker

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/website#105]
Fix all known errors found in AChecker from Ontario website suggested tool

See attached PDF:

[https://app.zenhub.com/files/112789607/237473d4-9037-4cb9-9932-e6654c9f33e0/download](https://app.zenhub.com/files/112789607/237473d4-9037-4cb9-9932-e6654c9f33e0/download)

Or run AChecker here against https://www.overture.bio/:

- https://achecker.ca/checker/

**Comment by samrichca** [comment]
https://6000aff8f676f157b833a995--overture.netlify.app

**Comment by b-f-chan** [comment]
Tested netlify above against AChecker, all Known Issues have been resolved:

![Screen Shot 2021-01-21 at 2.01.17 PM.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/31a618e2-14b5-47fb-8c10-b9d09750c7c0)

Ready to merge & close.

**Comment by samrichca** [comment]
@b-f-chan scope was changed to only the errors given by Ontario govt-recommended checker

also colours are resolved here: https://github.com/overture-stack/roadmap/issues/118

**Comment by b-f-chan** [comment]
@samrichca - Then testing on this ticket is complete.  If code review complete, let's move to Done!
