### ISSUE TITLE
Docs - missing "no results" search state

### ISSUE THREAD

**Issue by samrichca** [overture-stack/website#110]
Need to show a message when there's no results.

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/bd145574-acd2-4ec7-b4f5-13dd78df3143)

**Comment by samrichca** [comment]
https://601848589eb31a00f0d010ff--overture.netlify.app/

**Comment by b-f-chan** [comment]
Tested at netlify above:

- No results message correctly displays now if no matches are found in the search

Ready to close
