### ISSUE TITLE
Deployment Tasks for Doc Site

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/website#122]
These deployment tasks need to be done prior to doc site deployment on Mar 31:

1. Algolia search indexing:
    1. Check that this runs when the site is built/deployed on Netlify
    2. Check that Algolia keys are added in Netlify
2. Feature flag removal
    1. Docs template
    2. Docs landing page
    3. Navbar (megamenu)
    4. Layout - remove feature flag around <DocsWrapper>, keep isDocs condition
    5. Env.example & netlify.toml
    6. Footer menu

**Comment by samrichca** [comment]
- netlify is building & deploying the develop branch with branch deploys, and algolia works
- https://605e00c4618c2d721e88beb9--overture.netlify.app/
- any PRs against develop will automatically create a branch deploy link (like our QA links for GDC)
- I’ll turn that off after we go to prod next week ^^^
- it went smoothly except for netlify trying to use the wrong node version, which I have corrected

**Comment by b-f-chan** [comment]
Tasks completed, site deployed to prod
