### ISSUE TITLE
Investigate Solution for Gatsby Pre-Fetch/Hard Refresh Issue

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/website#132]
Internal links are currently standard HTML links which results in a hard refresh every time you switch pages. Also we can’t maintain the state of the left-hand navigation on Docs pages when you navigate between pages.

They were Gatsby/React links, but in some cases these links sent us to a blank page (i.e. when clicking on the megamenu or search results). This is a new issue likely stemming from adding significantly more content to the site. So I made them into HTML links as a hotfix.

Gatsby normally pre-fetches pages linked to the current page, but it can’t do that with the megamenu or search results because they’re hidden from view by default. It can also pre-fetch when you hover over a link, but we’re probably running into a timing issue now due to the larger amount of data. It can’t pre-fetch fast enough so it loads a blank page. 

Netlify link where this is happening: https://60647eb7469043007cabd856--overture.netlify.app/documentation/song/installation/installation/ 

I also got error 310 on another attempt. 
https://reactjs.org/docs/error-decoder.html/?invariant=300
https://reactjs.org/docs/error-decoder.html/?invariant=310 

https://github.com/gatsbyjs/gatsby/issues/4779
https://github.com/gatsbyjs/gatsby/issues/24398

Potential solutions, all of these need investigation:
- Force a refresh (the official Gatsby site does this)
- Enhance server side rendering
- Add a loader of some sort, when the app tries to update the route, wait for the data to fetch

**Comment by nooexcept** [comment]
I have the same issue as https://github.com/gatsbyjs/gatsby/issues/4779 and I wonder if both have the same causes, when going back to the page after sometime the links won't do anything, it won't show a blank page like it does for some, they just stop working. Doing a hard refresh fixes it, it also happens in build deployment.
