### ISSUE TITLE
Add Canarie acknowledgement to Overture Documentation site

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/website#137]
In all cases, Canarie logo links to Canarie site (open in new window): https://www.canarie.ca/

- [ ] Docs landing page: https://zpl.io/bPw4ovM
- [ ] DMS Docs - bottom of sidebar: https://zpl.io/2GDkdod
- [ ] DMS github page: 
![image](https://user-images.githubusercontent.com/18424138/113739534-e470ec80-96cd-11eb-8aa0-aa1e9d47ffdf.png)

**Comment by b-f-chan** [comment]
Added, verified, published to prod.  Closing.
