### ISSUE TITLE
Security Upgrade: June 092021

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/website#162]
A needed security upgrade has been indicated: 
![image](https://user-images.githubusercontent.com/15824252/121377965-c5cae400-c910-11eb-9a93-9d49b85f5a97.png)

**Comment by ciaranschutte** [comment]
closing in favour of https://app.zenhub.com/workspaces/overture-stack-5d2e058ff67cc800011fee6b/issues/overture-stack/website/174
