### ISSUE TITLE
Website - Security Alerts

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/website#174]
![image.png](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/01db1999-91d4-4031-8ac2-bbdc8f1aa2b2)

**Comment by ciaranschutte** [comment]
npm audit shows significantly more alerts: ![1.png](https://images.zenhubusercontent.com/5b58924328d06e60f1c19ac1/561f59f1-05ef-43d0-a929-f1b662fe2fb5)

**Comment by ciaranschutte** [comment]
gatsby is two major versions behind (most plugins also two versions behind)

**Comment by ciaranschutte** [comment]
installing latest version v4 solves half the security alerts vs trying to patch deep dependencies via some form of resolutions.

**Comment by ciaranschutte** [comment]
PR for QA: https://github.com/overture-stack/website/pull/181

**Comment by ciaranschutte** [comment]
@b-f-chan took a look and looks good.
updated our netlify so we don't auto publish
master is basically staging, and publishing is prod
