### ISSUE TITLE
Products Page (Requirement 2)

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/website#222]
## Mockup

https://www.figma.com/file/fXh58MfxEDh1ssgxQyPb5f/Overture_Refresh?type=design&node-id=1167-7351&mode=design&t=GvnRAniCZjF8gPQC-0

## Wiki

https://wiki.oicr.on.ca/display/OV/Products+Page

## Coordination Doc

https://wiki.oicr.on.ca/display/OV/Overture.bio+Co-ordination+Doc

**Comment by daniel-cy-lu** [comment]
https://deploy-preview-307--overture.netlify.app/products/ @patrickdsantos Patrick, this is the page preview of the Products Page! :) Welcome for your wonderful feedbacks !

**Comment by patrickdsantos** [comment]
This page is nearly perfect Daniel!! Well done! Below is my feedback for **post MVP**:

1. Double the padding between icon and title (apply to all sections)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1ZoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--425903e7ecbd37325e3a1681415bb6f6c522b9f7/Screenshot%202023-09-01%20at%203.29.36%20PM.png)

2. Reduce padding between sub-heading and body copy by half (apply to all sections)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2xoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--787a2b8c0b8e9bb987f2c9dcb5fea2342a8d7614/Screenshot%202023-09-01%20at%203.32.47%20PM.png)

3. There is a subtle grey gradient #F9F9F9 that starts at the top of the blue box and turns into white #FFFFFF (this is applied so there is a visual separation betwen the top of the DMS screenshot and the white background. Refer to mocks for direction. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEJoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--108771cc41946fd6a5167d14711979b63dbf7899/Screenshot%202023-09-01%20at%203.33.52%20PM.png)

4. Blue background should reach the edge of the browser window, no white space
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEZoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--720e4b9a6368fbd219018429c34993085809e85c/Screenshot%202023-09-01%20at%203.33.52%20PM%202.png)

5. When the width of the page is >1215px the Arranger icon is smaller than the rest of the other icons. Increase size to match other icons
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFZoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1fc3a9846f72bab562337b5f673798e969710953/Screenshot%202023-09-01%20at%203.41.55%20PM.png)

6. In mobile view, the Maestro icon does not appear centred. Move icon slightly to the left.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGRoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--49a28c5c50061fe766dfd9dbe43c79442e1e5a62/Screenshot%202023-09-01%20at%203.44.36%20PM.png)

7. Can't remember if this feedback was already captured but the footer is distorted when the window is >414px
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGhoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d5509ba81af8e47bd3a96d08990b1e450f69dd6e/Screenshot%202023-09-01%20at%203.48.55%20PM.png)
