### ISSUE TITLE
Acknowledgments Page (Requirement 6)

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/website#225]
## Resource

https://wiki.oicr.on.ca/display/OV/Acknowledgements+Page

## Mock-Up

https://oicr.slack.com/archives/D05CGEJUW2D/p1686585607756619

## Coordination Doc

https://wiki.oicr.on.ca/display/OV/Overture.bio+Co-ordination+Doc

**Comment by daniel-cy-lu** [comment]
Deploy preview link for this UI update: https://deploy-preview-271--overture.netlify.app/

**Comment by patrickdsantos** [comment]
Design Feedback:

1. Please update the illustration to this svg (placement is okay)
![controls_illustration.svg](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/9c68a1c5-4bc3-4a7e-8aca-03d2877bb7fd)

**Comment by daniel-cy-lu** [comment]
1. @patrickdsantos The Hero is a component that is used across the website now. The down side is that css need to be applied across all the heros, which make issues like uneven space. We want to come back later on to build hero for each specific pages.
