### ISSUE TITLE
Add Matomo tracking to Overture.bio (Requirement 5)

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/website#227]
### Still To Do

- Transfer Matomo account (set up with contact@overture.bio credentials)
- QA confirm version control / how not to break the website when using the tag manager

### Description:

Matomo Tag Manager Implementation should only involve adding the tag manager code to the header. From the tag manager UI on Matomo, we should be able to specify what to track (similar to google tag manager) without having to add code. If any specific information is required before hardcoding the tag manager into the website, reach out. 

If this is not possible, I can provide a specific list of metrics, and we can implement this via javascript. That said, a tag manager is ideal because it requires less development effort. 

### Resources

- [Overture.bio website repo here](https://github.com/overture-stack/website) 

- [Matomo setup doc](https://matomo.org/faq/on-premise/installing-matomo/#install-the-javascript-tracking-tag)

 - Sam will be a good contact as she's done quite a bit of research on specifically adding Matomo to a Gatsby site

- Please document any important information as you go to --> [Tracking metrics](https://wiki.oicr.on.ca/display/OV/Tracking+User+Metrics)

**Comment by daniel-cy-lu** [comment]
> Transfer Matomo account (set up with contact@overture.bio credentials)
We end up using IT's Matomo server. We don't need to create our own cloud server.
