### ISSUE TITLE
0. Scrape Github API Metrics

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/website#228]
### Description:

Pull Metrics from the GitHub API into google sheets or Excel doc; the goal is to be able to use this for monthly/Quarterly reports

Metrics should cover the following repos:

- Ego, Song, Score, Maestro, Arranger, DMS
- Ignore Hourly

Spreadsheet should update automatically

### Resources

API Quickstart Guide:
https://docs.github.com/en/rest/quickstart?apiVersion=2022-11-28

See Metrics (Community, Traffic & Statistics)
https://docs.github.com/en/rest/metrics/community?apiVersion=2022-11-28

- Metrics pulled from the [Overture-Stack Github](https://github.com/overture-stack/) 
- [Overture Github "Packages"](https://github.com/orgs/overture-stack/packages) Unsure of what differentiates packages from containers (google says a manifest file), but Github doesn't really clarify

- Please document any important information as you go to --> [Tracking metrics](https://wiki.oicr.on.ca/display/OV/Tracking+User+Metrics)

**Comment by daniel-cy-lu** [comment]
Using Octokit library and made an Node.js app. Once the app is ran, a folder is generate at desktop, json files of each metric specific to each repo are also generated within this folder. These file holds the API endpoint data.
