### ISSUE TITLE
Landing Page (Requirement 3)

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/website#229]
**Mockup**

https://www.figma.com/file/fXh58MfxEDh1ssgxQyPb5f/Overture_Refresh?type=design&node-id=1098-6663&mode=design&t=GvnRAniCZjF8gPQC-0

**Wiki**

https://wiki.oicr.on.ca/display/OV/Landing+Page

**Co-ordination Doc**

https://wiki.oicr.on.ca/display/OV/Overture.bio+Co-ordination+Doc

**Comment by daniel-cy-lu** [comment]
@patrickdsantos Hi Patrick, the UI for the four pages are complete. They are for the desktop/desktop wide version. The deploy preview link is here: https://deploy-preview-271--overture.netlify.app/

Just a note, I haven't deleted contact us page because its link is still in the footer

**Comment by patrickdsantos** [comment]
Design QA

1. Centre title and body copy to the width of the browser
![Screenshot 2023-07-24 at 2.46.39 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/4276b61c-5f56-435d-9436-5c00533da62a)

2. Move illustration to the left as well as text. 
![Screenshot 2023-07-24 at 2.46.46 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/b6edf070-c8e8-44a7-b7ad-0a6c3304ef14)

3. Centre the following sections:
![Screenshot 2023-07-24 at 2.59.53 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/fa476b76-5019-44b1-9bf9-3841e2647e48)
![Screenshot 2023-07-24 at 2.59.59 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/decabf1e-f6c9-4f86-b359-00be142105b7)
![Screenshot 2023-07-24 at 3.00.06 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/be2a4629-1027-48e4-ba28-2ab3cb7a6104)
![Screenshot 2023-07-24 at 3.00.11 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/393f9a3d-0a4a-4e46-a363-797ff7f31d5e)

4. The hover state should only effect the logo, not the line selector (this is a selected state)
![Screenshot 2023-07-24 at 3.00.50 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/f7ee8c3b-e193-47dd-b0ad-32d110355068). 

5. Remove the white space in between this section and the footer. The square should overlap on top of the footer.
![Screenshot 2023-07-24 at 3.07.50 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/8b0ba1bc-dc2b-4a07-862f-494dab17c875)

6. Make sure the drop down menu is the same width of the browser
![Screenshot 2023-07-24 at 3.10.58 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/2ecb0eb7-04b9-4b2f-a2d2-dd577a17f7c4)

7. When dropdown is expanded, flip this arrow so it is pointing upwards.  
![Screenshot 2023-07-24 at 3.11.19 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/b09cf844-b6f2-4eed-886e-987221c520c8)

8. Remove hover state from this element. This will eventually be an animation.
![Screenshot 2023-07-24 at 3.13.48 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/0f943830-ed89-4652-8798-25820dd9fdf8)

9. Remove hover state from these arrows
![Screenshot 2023-07-24 at 3.15.41 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/6d53c84a-4b59-4fbf-8702-dfb9a2f498fd)

**Comment by daniel-cy-lu** [comment]
Working off a new branch, please use this new deploy website link. All the previous changes on other pages are in affect in this new link. https://deploy-preview-277--overture.netlify.app/ 

Still looking into 1-3.

4. The style is updated. The underline doesn't change when logos are hovered.

**Comment by daniel-cy-lu** [comment]
6. drop down menu is now full width of the browser. The grey(left) section will always take up 50% of the width and each of the right (white) section will take up 25% of the width. 
![Screenshot 2023-07-27 at 12 08 21 PM](https://github.com/overture-stack/website/assets/79996555/adb9374b-7c1b-4489-95e4-086ac6e59740)
![Screenshot 2023-07-27 at 12 08 09 PM](https://github.com/overture-stack/website/assets/79996555/0667d432-8d43-4cba-acee-90bb78b08198)

**Comment by daniel-cy-lu** [comment]
7. When the dropdown menu is opened, the documentation arrow will point upward.
![Screenshot 2023-07-27 at 2 19 12 PM](https://github.com/overture-stack/website/assets/79996555/15ef9581-90eb-45df-be66-6f9498c7e4b3)

**Comment by daniel-cy-lu** [comment]
8. will build a new animation button for this part. Will leave this one out for now.
