### ISSUE TITLE
Case Studies Page (Requirement 7)

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/website#236]
**Mockup**

https://www.figma.com/file/fXh58MfxEDh1ssgxQyPb5f/Overture_Refresh?type=design&node-id=1167-8305&mode=design&t=GvnRAniCZjF8gPQC-0

**Case Studies Page Wiki Doc:**

https://wiki.oicr.on.ca/display/OV/Case+Studies+Page

**Co-ordination Doc**

https://wiki.oicr.on.ca/display/OV/Overture.bio+Co-ordination+Doc

**Comment by daniel-cy-lu** [comment]
Deploy preview link for this UI update: https://deploy-preview-271--overture.netlify.app/

**Comment by daniel-cy-lu** [comment]
1. Update: Both hover and selected state shadow is as above. 
![Screenshot 2023-07-20 at 10 00 45 AM](https://github.com/overture-stack/website/assets/79996555/400de3f5-6496-45ea-9cb4-2eefe264c598)

**Comment by daniel-cy-lu** [comment]
4. I added an additional breakpoint to make space for even. I added an ultra wide breakpoint, so we don't cater when we are slightly above 1441px. @patrickdsantos
