### ISSUE TITLE
NavBar Updates & Footer Updates (Requirement 1)

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/website#238]
**Mockup**

https://www.figma.com/file/fXh58MfxEDh1ssgxQyPb5f/Overture_Refresh?type=design&node-id=117-3331&mode=design&t=GvnRAniCZjF8gPQC-0

**Navbar & Footer Updates Doc**

https://wiki.oicr.on.ca/display/OV/NavBar+and+Footer+Updates

## Coordination Doc

https://wiki.oicr.on.ca/display/OV/Overture.bio+Co-ordination+Doc

**Comment by daniel-cy-lu** [comment]
Deploy preview link for this UI update: https://deploy-preview-271--overture.netlify.app/

**Comment by patrickdsantos** [comment]
Design Feedback:

1. Update footer to new designs 
![Screenshot 2023-07-19 at 11.47.12 AM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/fe800909-d34f-42f0-92f4-8dc37ae675a3)

2. Add arrow to Documentation link (refer to new designs)
![Screenshot 2023-07-19 at 11.47.18 AM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/97648579-c45b-42e2-996c-ce210bdb4e6a)

3. Update documentation drop down to match mock designs. See mock screenshot below:
![Screenshot 2023-07-19 at 12.10.02 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/35cccc96-50be-4545-aefd-0feb46036cc3)

4. Remove product drop down menu
![Screenshot 2023-07-19 at 12.10.49 PM.png](https://images.zenhubusercontent.com/6380ec3edf8a8d3caabd8496/7b6a9ea7-3fc0-4b58-97c1-3352f25b3e30)

**Comment by daniel-cy-lu** [comment]
1. update two items in the Footer
<img width="1345" alt="Screenshot 2023-07-20 at 10 44 36 AM" src="https://github.com/overture-stack/website/assets/79996555/d6acd0f2-3e61-425c-8c39-e15a24f782ef">

**Comment by daniel-cy-lu** [comment]
2. @patrickdsantos arrow added next to Documentation in navbar
<img width="714" alt="Screenshot 2023-07-20 at 11 34 13 AM" src="https://github.com/overture-stack/website/assets/79996555/efb429c9-f828-48a1-976b-c3ee0928a141">

**Comment by daniel-cy-lu** [comment]
3. @patrickdsantos update items in documentation sub menu.
![Screenshot 2023-07-20 at 2 55 39 PM](https://github.com/overture-stack/website/assets/79996555/5ecc1a62-2f81-40b8-8688-df5fae21f8b0)

**Comment by daniel-cy-lu** [comment]
4. @patrickdsantos Remove Product Link Submenu
