### ISSUE TITLE
When a dedicated component page does not exist on Overture.bio, redirect to the Github repo

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/website#26]
Adding a small icon to indicate the user will be redirected to GitHub.

Enrolment => https://github.com/overture-stack/enrolment
Usage => https://github.com/CancerCollaboratory/billing
Billing => https://github.com/CancerCollaboratory/billing
Score => https://github.com/overture-stack/score
Jupyter => https://github.com/overture-stack/Jupyter
OncoJS => https://github.com/oncojs
Ego => https://github.com/overture-stack/ego
Persona => https://github.com/overture-stack/persona

Those updates should be done in the middle sections
![screen shot 2018-01-11 at 3 17 05 pm](https://user-images.githubusercontent.com/5667028/34845331-86eb9ba2-f6e2-11e7-8b9e-caec42cc4391.png)

And the footer:
![screen shot 2018-01-11 at 3 17 36 pm](https://user-images.githubusercontent.com/5667028/34845348-937f5bec-f6e2-11e7-8eb2-7f98d7d24b4f.png)

**Comment by alex-wilmer** [comment]
https://github.com/overture-stack/website/commit/fbceb1ac562e614e00f296555f2c3f93cb499d4c
