### ISSUE TITLE
Case Studies Page Responsive CSS

### ISSUE THREAD

**Issue by daniel-cy-lu** [overture-stack/website#288]
Create css responsive for Case Studies Page when view with mobiles and tablets.

**Comment by daniel-cy-lu** [comment]
https://deploy-preview-285--overture.netlify.app/case-studies/ @patrickdsantos

**Comment by daniel-cy-lu** [comment]
2. The screenshot now line up on the left with the text above it in desktop width. Here are two desktop width showing the screenshot is lined up.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWNoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ef5df200868f2483047c85e56527fc95ad771c08/Screenshot%202023-08-21%20at%202.50.52%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWdoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ccae871a2ead0fcd9a9f7892520380fa7c663cf0/Screenshot%202023-08-21%20at%202.51.06%20PM.png)

I kept the tablet and mobile mode the same where the screenshot will be centered. Here is a screenshot. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXNoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7626330cd58e279de1f6c706c86e52077d47b772/Screenshot%202023-08-21%20at%202.51.20%20PM.png)

**Comment by daniel-cy-lu** [comment]
4. Fix this issue. The navbar will hide the section on its right rather than the left. Please see these two screenshots, at the width between 1162px and 1024px where this issue was occurring.[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjRoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--44aad0659b10457668eacbcd6656c7dfea24055f/Screenshot%202023-08-21%20at%203.20.05%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjhoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4db8f5d8921f27afbb87690d06f3c3a9d32495f4/Screenshot%202023-08-21%20at%203.20.18%20PM.png)

**Comment by patrickdsantos** [comment]
Wonderful work here @daniel-cy-lu  !!

Everything looks great, waiting to see changes pertaining to feedback 5. However if feedback 5 ends up being a heavy lift, we can leave it for post MVP. 

Tagging @MitchellShiell for visibility!
