### ISSUE TITLE
Acknowledgement Page Responsive CSS

### ISSUE THREAD

**Issue by daniel-cy-lu** [overture-stack/website#289]
Create css responsive for Acknowledgement Page when view with mobiles and tablets.

**Comment by daniel-cy-lu** [comment]
https://deploy-preview-293--overture.netlify.app/acknowledgements/ @patrickdsantos

**Comment by patrickdsantos** [comment]
Wonderful job Daniel! This page is looking fantastic, just a couple of notes below:

1.  Decrease padding of hero text when screen width is >767px (see image attached). 
Currently there's 80px of padding plus and additional 50px. Can we reduce so the padding is 50px total?
![Screenshot 2023-08-21 at 10 46 35 AM](https://github.com/overture-stack/website/assets/116736040/b5c16826-493a-4a91-b185-a46739884e13)

2. Accommodate screens that are between 360px and 426px.
Right now, when the window is smaller than 426px wide, the hero copy and body copy are no longer centred and starts to cut off. Could we continue to wrap text into a new line until 360px?
![Screenshot 2023-08-21 at 10 45 21 AM](https://github.com/overture-stack/website/assets/116736040/5f02726e-9564-401a-8c4d-5d2b91418481)

**Comment by patrickdsantos** [comment]
Additional note for @daniel-cy-lu & @MitchellShiell 

All feedback provided above can be made post-MVP launch.
