### ISSUE TITLE
Post-MVP Mega Ticket 

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/website#311]
The following is a mega-ticket for all post-MVP feedback; this can be later distributed into smaller ticket items.

# Table of Contents

# General

- [x] Website window is magnified when first loaded on a mobile

# Landing Page

- [ ] Center logo, swap hamburger icon to the one used in the mocks, move to left side of the screen and add "Get Started" button to the top right hand corner. 
![Screenshot 2023-08-21 at 4 13 32 PM](https://github.com/overture-stack/website/assets/116736040/44719b65-af29-48b2-97a4-122ddb470e63)

- [x] Similar feedback from ticket #289 , accommodate screens that are between 360px and 426px.
Right now, when the window is smaller than 426px wide, the hero copy and body copy are no longer centred and starts to cut off. 
![Screenshot 2023-08-21 at 3 53 38 PM](https://github.com/overture-stack/website/assets/116736040/6c4aa490-18bb-40c9-a741-51c877f83198)

- [x] This was not reflected in the mocks but this area looks a bit squished. Can we increase the padding in between these columns? (try adding additional 10px in between each)
![Screenshot 2023-08-21 at 3 58 46 PM](https://github.com/overture-stack/website/assets/116736040/81df51a3-30be-40ea-a36b-9c8008610e92)

- [x]  These elements should stack in a single column, refer to mocks for direction.
![Screenshot 2023-08-21 at 4 17 39 PM](https://github.com/overture-stack/website/assets/116736040/307f8c87-5abb-4d9a-ba5e-2acdca4b617d)

- [x] The spacing on the right side is strange, also reduce size of the image so that it's width is 450px.
![Screenshot 2023-08-21 at 4 21 24 PM](https://github.com/overture-stack/website/assets/116736040/3ef3647d-b340-4ed3-9dee-88013459400a)

- [x] Increase margin between arrow and image. Try 30px
![Screenshot 2023-08-21 at 4 28 37 PM](https://github.com/overture-stack/website/assets/116736040/fd9ce257-3a6a-4f03-a13f-8de8f45184f7)

- [x] Increase padding in between these elements. Try 30px
![Screenshot 2023-08-21 at 4 30 27 PM](https://github.com/overture-stack/website/assets/116736040/6067208f-9693-4e86-bc07-20e7d3f413c0)
- [x] Increase spacing between each column. Try 30px
![Screenshot 2023-08-21 at 4 32 56 PM](https://github.com/overture-stack/website/assets/116736040/e6aa62ce-5be3-48f0-96b9-a6cd19b7cdaf)

- [x] Add more padding between illustration and header copy. Try 30px
![Screenshot 2023-08-21 at 4 37 19 PM](https://github.com/overture-stack/website/assets/116736040/0250cafb-d334-4856-8406-5f51f7039b97)

- [x] Reduce padding above to match the bottom of the grey box
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWM5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--829bb54e910f4e37ad6b9f077d3da69863d49c97/Screenshot%202023-08-25%20at%2011.47.28%20AM.png)

# Products Page

- [x] Double the padding between icon and title (apply to all sections)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1ZoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--425903e7ecbd37325e3a1681415bb6f6c522b9f7/Screenshot%202023-09-01%20at%203.29.36%20PM.png)

- [x] Reduce padding between sub-heading and body copy by half (apply to all sections)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2xoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--787a2b8c0b8e9bb987f2c9dcb5fea2342a8d7614/Screenshot%202023-09-01%20at%203.32.47%20PM.png)

- [x] There is a subtle grey gradient #F9F9F9 that starts at the top of the blue box and turns into white #FFFFFF (this is applied so there is a visual separation betwen the top of the DMS screenshot and the white background. Refer to mocks for direction. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEJoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--108771cc41946fd6a5167d14711979b63dbf7899/Screenshot%202023-09-01%20at%203.33.52%20PM.png)

- [x] When the width of the page is >1215px the Arranger icon is smaller than the rest of the other icons. Increase size to match other icons
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFZoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1fc3a9846f72bab562337b5f673798e969710953/Screenshot%202023-09-01%20at%203.41.55%20PM.png)

- [x] In mobile view, the Maestro icon does not appear centred. Move icon slightly to the left.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGRoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--49a28c5c50061fe766dfd9dbe43c79442e1e5a62/Screenshot%202023-09-01%20at%203.44.36%20PM.png)

- [x] Can't remember if this feedback was already captured but the footer is distorted when the window is >414px
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGhoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d5509ba81af8e47bd3a96d08990b1e450f69dd6e/Screenshot%202023-09-01%20at%203.48.55%20PM.png)

# Case Studies Page

- [x] If possible, remove white padding on the both sides and allow the grey buttons to be cropped right to the edge of the window. 
![Screenshot 2023-08-21 at 11 51 45 AM](https://github.com/overture-stack/website/assets/116736040/f78ed39d-ec2f-4f70-94a4-a01524158035)

# Acknowledgements Page

- [x] Decrease padding of hero text when screen width is >767px (see image attached). 
Currently there's 80px of padding plus and additional 50px. Can we reduce so the padding is 50px total?
![Screenshot 2023-08-21 at 10 46 35 AM](https://github.com/overture-stack/website/assets/116736040/b5c16826-493a-4a91-b185-a46739884e13)

- [x] Accommodate screens that are between 360px and 426px.
Right now, when the window is smaller than 426px wide, the hero copy and body copy are no longer centred and starts to cut off. Could we continue to wrap text into a new line until 360px?
![Screenshot 2023-08-21 at 10 45 21 AM](https://github.com/overture-stack/website/assets/116736040/5f02726e-9564-401a-8c4d-5d2b91418481)

**Comment by daniel-cy-lu** [comment]
@patrickdsantos Patrick, here is the deploy preview link. Thank you for reviewing it! :D https://deploy-preview-327--overture.netlify.app/

**Comment by daniel-cy-lu** [comment]
1. The underline is static now. (I make just the cursor to be a pointer at the hover state. Is this enough to let user know they can click on it? Thanks Patrick!)

**Comment by daniel-cy-lu** [comment]
2. The title is lined up with the top of the image. These are what I've done to the css. I set a min-height to the image to prevent it from scaling too short. Please check starting 1035px, the image might look squished horizontally. But it's smoothen out as we have more space for image to stretch out. I edit the text font size from 20px to 18px to create space for Kids First case's text. This case has slightly too much text. I also use "It" for "Overture" in the second sentence.

**Comment by daniel-cy-lu** [comment]
3. Added top margin to "Our Products" section to match that of "Getting Started"

**Comment by MitchellShiell** [comment]
12. Our Products Hero title in line with content

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanJpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4f0d8787d503a498b6c8429feaa6fd6b7f675a4a/Screenshot%202023-09-27%20at%2011.49.45%20AM.png)

**Comment by daniel-cy-lu** [comment]
7. Image max-width set to 1000px.

**Comment by daniel-cy-lu** [comment]
8. Text section is set to max-width: 1000px as well.

**Comment by daniel-cy-lu** [comment]
9. At mobile view, the icons are 50X50px. The gap between the text and icon/title are reduced.

**Comment by daniel-cy-lu** [comment]
10. The image was vertically centered which caused the misalignment. Removed the vertically centered behaviour and instead to have the image to always be at the top of the container. The image now lines up with the top of the text on the rightside.

**Comment by daniel-cy-lu** [comment]
11. The space between the logos are reduced by 15px.

**Comment by daniel-cy-lu** [comment]
@MitchellShiell The Cell phone view auto zoom and the misalignments, such as the original comments from "Landing Page" section are resolved. This is the issue from the Landing Page section: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblh3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6a396610e1cc100449a69d91f0366469c2ded9c4/Screenshot%202023-09-29%20at%2012.14.20%20PM.png)

**Comment by daniel-cy-lu** [comment]
5. Burger menu now is full screen. I am using the grey area with cubes as filler. And I decided to remove the cubes when documentation sub menu is opened. Because there is limited space to have all three cubes.

**Comment by daniel-cy-lu** [comment]
12. The Hero Title is lined up with Section Titles now in ultra wide and wide desktop views. They cannot always be lined up in table and desktop view, because they don't "move" together when screen size is adjusted. This is due to certain width is needed for the section for this page content.

**Comment by daniel-cy-lu** [comment]
6. The menu is now is a three column width. Note: I updated a few css to achieve this. Please help me double check all views to make sure nothing is buggy after the changes. It looks good to me :)

**Comment by patrickdsantos** [comment]
@daniel-cy-lu INCREDIBLE WORK!!! Website is nearly perfect!! Thank you for all your hard work - I just have one last piece of feedback. 

1. My fault for not explaining properly, for the logos at the top of the homepage, the logos can increase in size for the hover state. I'd say increase by 15%? But keep the underline the same size. Thank you!

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaS8yIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d7dcde52b46c5ec33a8f83a38361f06123d1fda6/Screenshot%202023-10-02%20at%2010.14.21%20AM.png)
