### ISSUE TITLE
Landing Page Polish

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/website#316]
## Deploy Preview: 

https://deploy-preview-315--overture.netlify.app/

## Pull Request

https://github.com/overture-stack/website/pull/315

Getting there! Please review the changes and have a run through the following.

To do on the landing page:

- [ ] Scaling of hero subtext
- [ ] Scale of Hero Image (or enlarge the hero section so the icons are not cut off in the image)
- [ ] Fix Carousel test and button alignment
- [ ] add Href to carousel portal images that open the portal in a new tab (optional based on complexity; Gatsby is weird for links)
- [ ] Fix Maroon Cube (sorry I broke it)
- [ ] Update Services button to link to services page
- [ ]  Underline the titles in the getting started section (to look like links similar to the components in our products above

Nav Bar
- [ ] Remove community (for now can comment out if possible)

**Comment by patrickdsantos** [comment]
Site is looking fantastic!! Just a few pieces of feedback, can be done post MVP:

1. Hamburger menu when Documentation is expanded should take up full window when open. Use the block image to hide the website underneath.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdENJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1206f9c75c00d986da1f5f2951e64f15527cfdcc/Screenshot%202023-09-11%20at%201.06.29%20PM.png)

2. Not sure if this is a Netlify issue but the footer has extra padding on the right side when in mobile view.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEtJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb031c2afcb8b81854c1790b7b1f24cfc9e425bc/Screenshot%202023-09-11%20at%201.07.25%20PM.png)

3. Same feedback as #2 for this section
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdE9JIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4be35bcbb5a680ec5ff3a766a082e1e14eb8334b/Screenshot%202023-09-11%20at%201.08.13%20PM.png)

4. Image is slightly off-centre
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGFJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--459f7a30fe8f32bbc52349a545ccbacfa22bbe52/Screenshot%202023-09-11%20at%201.08.47%20PM.png)

That's all! Thanks again!
