### ISSUE TITLE
Add "Join us on Slack" button

### ISSUE THREAD

**Issue by kcullion** [overture-stack/website#36]
- [x] Add "Join us on Slack" button to the main nav (to the left of "Get Started")
The link will open a page similar to: http://slack.torontojs.com/
- [x] Add "Join us on Slack" as a button on the contact page

Ping Kim for assets
See mockup: https://invis.io/G3L6UX9W9H6#/296968704_Contact

**Comment by hlminh2000** [comment]
I just addressed the Slack button feature as that was urgent. The rest of the change requests have been moved to this issue: https://github.com/overture-stack/website/issues/38
