### ISSUE TITLE
BUG - donwload page mentions upload

### ISSUE THREAD

**Issue by mcourtot** [overture-stack/website#387]
https://www.overture.bio/documentation/score/user-guide/download/

the last sentence "If successful the Score Client will indicate the upload has completed." should refer to download instead of upload. Possibly needs updating the info box just before which talks about "To understand more about key terms in Overture's data submission workflow" - I appreciate the manifest terms comes form the submission doc but it is odd here - maybe "To understand more about key terms in Overture's data ~~submission~~ workflow**S,** check this guide on [data submission using Song and Score](https://www.overture.bio/documentation/song/user/submit/)."

**Comment by MitchellShiell** [comment]
Addressed in the following PR:
https://github.com/overture-stack/website/pull/390
