### ISSUE TITLE
BUG - feedback icons

### ISSUE THREAD

**Issue by mcourtot** [overture-stack/website#388]
It is not clear what the feedback icons do, eg at https://www.overture.bio/documentation/score/user-guide/commands/

![Screenshot 2024-05-17 at 2 57 10 PM](https://github.com/overture-stack/website/assets/2214135/f52dbf77-1eb0-4d89-8a6f-45d2b8dca2ac)

Once clicked it seems 'activated' (?) in a white frame, but nothing happens, and I can't deactivate it or change my mind and select the other one.

**Comment by MitchellShiell** [comment]
Vestigial feature, the original intention was to use a tag manager to track clicks on each icon (limiting one click per page view), this can definitely be improved
