### ISSUE TITLE
BUG - broken link 'Make a contribution'

### ISSUE THREAD

**Issue by mcourtot** [overture-stack/website#389]
In the blue footer at the bottom of the page eg https://www.overture.bio/documentation/score/user-guide/commands/, the link make a contribution redirects to https://github.com/overture-stack/website/tree/develop/markdown/documentation/score/user-guide/commands.md which is 404

![Screenshot 2024-05-17 at 2 59 47 PM](https://github.com/overture-stack/website/assets/2214135/7b75abc7-1e54-4474-ac1e-b706dcf1c5f4)

**Comment by MitchellShiell** [comment]
good find, somthing must have changed, will investigate
