### ISSUE TITLE
[Design Review] - QuickStart content update

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/website#395]
## Summary of request

- We have new demo content including the Overture Demo portal and the Overture Quickstart that needed new CTAs and pages on the website. 
    - The Demo portal is to give new prospective users a quick look at our platform 
    - The Quickstart is the main way to get users up and running with our platform on there machine alongside our guides and documentation.  

## Details

I am looking for review on the following pages/updates linked below

- Major Updates
    - [Updated landing page](https://deploy-preview-385--overture.netlify.app/)
    - [Updated getting started page](https://deploy-preview-385--overture.netlify.app/getting-started/)

- Minor Updates
    - [Bottom of product page](https://deploy-preview-385--overture.netlify.app/products/)
    - Documentation Meganav menu

## Additional details

- This issue/ticket is linked to the [Overture Guides working branch/PR](https://github.com/overture-stack/website/pull/385)

**Comment by patrickdsantos** [comment]
Great work @MitchellShiell !! There is nothing critical about the updates, feedback below is really just suggestions:

### Landing Page

1. After clicking on "View Demo" if the user comes back to the homepage, the button is stuck in pressed down state. Is this desired behaviour?
<img width="1714" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGVJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bac2fb969729013b566e5e804a566457fc6cb0f6/Screenshot%202024-06-20%20at%209.27.04%E2%80%AFAM.png" alt="Screenshot 2024-06-20 at 9.27.04 AM.png" />

2. Look into increasing the padding of text in mobile view.
<img width="1050" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGlJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4109c17c407154d1e0ebfa9b4010928ee4683452/Screenshot%202024-06-20%20at%209.33.36%E2%80%AFAM.png" alt="Screenshot 2024-06-20 at 9.33.36 AM.png" />

3. In mobile view, text runs over window.
<img width="1070" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0417eb714ee2adaa3bb0d5e86b59e6c3d5cad2e/Screenshot%202024-06-20%20at%209.33.48%E2%80%AFAM.png" alt="Screenshot 2024-06-20 at 9.33.48 AM.png" />

### Getting Started Page
1. Is it possible to make these bullet points align with the top?
<img width="943" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMktJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12f423c403e22bffc7c5d848cd5a8e5783dea1cb/Screenshot%202024-06-24%20at%2010.44.54%E2%80%AFAM.png" alt="Screenshot 2024-06-24 at 10.44.54 AM.png" />

2. Explore increasing the two column widths or implementing just one column for these bullet points in mobile view.
<img width="534" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnFJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7c6b0e7a46c58bb792242aebb9e74051c6c5c95/Screenshot%202024-06-24%20at%2010.49.23%E2%80%AFAM.png" alt="Screenshot 2024-06-24 at 10.49.23 AM.png" />

No feedback for bottom of product page or documentation mega menu

**Comment by MitchellShiell** [comment]
Gracias Patrick!
