### ISSUE TITLE
Clicking on a tab should trigger a scroll position change, which then triggers the waypoint to activate

### ISSUE THREAD

**Issue by cheapsteak** [overture-stack/website#5]
Sorry to have to have you clean up after me

Currently the [`onSelect` for the tabs directly sets the active tab](https://github.com/overture-stack/website/blob/7199f0b9dbab6fe22dc9aefbc580900ee8acbfc6/src/components/home/ProductsSection.js#L85)
[Waypoints also set the active tab](https://github.com/overture-stack/website/blob/7199f0b9dbab6fe22dc9aefbc580900ee8acbfc6/src/components/home/ProductsSection.js#L114)

This results in confusing behaviour. After clicking a tab, the content changes, but the scroll position does not, so scrolling somewhere would cause the user to activate a tab that doesn't make sense

Switching the `onSelect` for tabs to scroll to the corresponding Waypoint element for that tab would solve this problem

**Comment by rosibaj** [comment]
no longer valid.
