### ISSUE TITLE
Update product status: Arranger and Maestro

### ISSUE THREAD

**Issue by kcullion** [overture-stack/website#79]
Please update the product status of Arranger to **Release Candidate** on these pages:

- [x] https://www.overture.bio/products/arranger
- [ ] ReadMe: https://github.com/overture-stack/arranger

![image](https://user-images.githubusercontent.com/18424138/92800894-1f52b200-f383-11ea-989e-19efabba4090.png)

Please update the product status of Maestro to **Release Candidate** on the website page:

- [x] https://www.overture.bio/products/maestro

**Comment by samrichca** [comment]
I don't have access to this >>> https://github.com/overture-stack/arranger

https://5fa02ecbe1f7c356d207912b--overture.netlify.app/

**Comment by samrichca** [comment]
https://github.com/overture-stack/website/pull/92

**Comment by samrichca** [comment]
https://github.com/overture-stack/arranger/pull/630

**Comment by b-f-chan** [comment]
Tested website changes at netlify link above:

- Arranger, Maestro pages both correctly indicate Release Candidate stage

Checked PR 630 for Arranger:

- README updated from BETA to RELEASE CANDIDATE; but PR will be formally reviewed/approved in due process

This ticket is good to close
