### ISSUE TITLE
Move Sapien Section to Top of OncoJS Page on Overture Website

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/website#87]
Move the Sapien section in the OncoJS page on the Overture website to the top, before Lolliplot

This is to make Sapien more prominent

Maintain the alternating white/black backgrounds for each section, starting with white (so now Sapein will be white, followed by Lolliplot gray, etc)

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/9d41b2ab-970b-42ec-b8a9-40084643bf0d)

**Comment by samrichca** [comment]
https://5f9b19d6df0a3a459ff7191a--overture.netlify.app/products/oncojs/

**Comment by b-f-chan** [comment]
Tested at netlify link above:

- Sapien section correctly moved to top of page (first feature displayed)
- Background colour correctly starts with white and alternates with gray like existing page
- Description & image correctly start with description on left, image on right, and alternates like existing page

Testing successful, ready to close

**Comment by b-f-chan** [comment]
Extra note, this works fine (same results as above) on mobile as well
